/* Offline product presentation. All examples and source statements are fictional. */
const $=q=>document.querySelector(q);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tour=['SCR09','SCR03','SCR05','SCR07','SCR08','SCR10','SCR12','SCR19','SCR22','SCR24','SCR21'];
const stages=['Meet the company','Identify the sources','See the common goal','Check with an expert','Publish safely','Prepare once','Collect evidence','Assess independently','Spot a source change','Decide what changes','Issue the report'];
const takeaways=['Missing scope stays unknown.','Source rights are checked per operation.','A common goal keeps every extra duty visible.','A qualified person decides catalogue meaning.','Guarded software publishes after approval.','Preparation is separate from audit conclusions.','A stored file is not proof of effectiveness.','Each audit makes its own evidence decision.','A failed source check is never “no change”.','Company adoption and audit amendment differ.','A report retains its exact source and evidence basis.'];
const roles={Company:'Company',Auditor:'Auditor',Curation:'Catalogue expert',Administration:'Service administration',All:'Shared tools'};
const moduleLabels=['People and access','Source library','Compare requirements','Expert review and publication','Company scope','Prepare for audits','Evidence library','Connect existing systems','Plan audit missions','Audit fieldwork','Findings and reports','Monitor source changes','Assess business impact','Tasks and conversations','Search and optional writing help','Run the service','Plans and usage','Import, export and exit'];
function icon(name){let p={Company:'M4 21V7h10v14 M14 12h6v9 M8 10h2 M8 14h2',Auditor:'M14 14 21 21 M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0',Curation:'M12 3 20 6v6c0 5-8 9-8 9s-8-4-8-9V6Z M8 12l3 3 5-6',Administration:'M4 6h16 M4 12h16 M4 18h16',arrow:'M4 12h16 M14 6l6 6-6 6',layers:'M4 8 12 3 20 8 12 13Z M4 12 12 17 20 12 M4 16 12 21 20 16'}[name]||'M4 8 12 3 20 8 12 13Z M4 12 12 17 20 12 M4 16 12 21 20 16';return `<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${p}"/></svg>`}
function card(title,copy,to,type='layers'){return `<a class="card" href="${to}"><span class="card-icon">${icon(type)}</span><h3>${esc(title)}</h3><p>${esc(copy)}</p><b>Explore <span aria-hidden="true">→</span></b></a>`}
function matchDiagram(){return `<div class="match" aria-label="Two illustrative sources linked to one shared objective with an additional duty retained"><div class="source-group"><div><span>Illustrative source</span><strong>PCI DSS</strong><p>Review privileged access to payment systems.</p></div><div><span>Illustrative source</span><strong>DORA</strong><p>Review privileged access in the resilience example.</p></div></div><span class="connector" aria-hidden="true">${icon('arrow')}</span><div class="shared"><span>Shared objective</span><strong>Review privileged access and record the result</strong><p>One clear preparation view for the company.</p></div><span class="connector" aria-hidden="true">${icon('arrow')}</span><div class="difference"><span>Difference retained</span><strong>Why was access retained?</strong><p>The extra justification stays linked to its source.</p></div></div>`}
function home(){return `<section class="hero"><div><span class="eyebrow">An eleven-step product demonstration</span><h1>Prepare one clear view.<br><em>Keep every obligation visible.</em></h1><p class="lead">Northstar Pay prepares for two audits. See how illustrative Payment Card Industry Data Security Standard (PCI DSS) and Digital Operational Resilience Act (DORA) requirements connect to company evidence, expert approval and independent audit work.</p><div class="buttons"><a class="btn" href="#tour/0">Walk through the example ${icon('arrow')}</a><a class="btn light" href="#engine">Understand the matching engine</a></div><p class="fine">Fictional company · Invented requirements · No real audit or source text</p></div><div class="hero-stats"><span>THE STORY AT A GLANCE</span><div><b>2</b> source views</div><div><b>1</b> shared objective</div><div><b>1</b> extra duty retained</div><div><b>2</b> independent audit judgements</div></div></section><section class="section"><span class="eyebrow">Follow the case</span><h2>From source obligation to audit report</h2><div class="route-grid">${tour.map((id,i)=>`<a href="#tour/${i}"><span>${String(i+1).padStart(2,'0')}</span><b>${esc(stages[i])}</b><small>${esc(takeaways[i])}</small></a>`).join('')}</div></section><section class="section"><span class="eyebrow">Four responsibilities</span><h2>See what each person actually does</h2><div class="grid">${card('Company','Maya owns scope; Clara supplies versioned evidence.','#workspace/Company','Company')}${card('Auditor','Alex evaluates evidence for a mission and signs the exact report.','#workspace/Auditor','Auditor')}${card('Catalogue expert','A qualified expert approves exact catalogue meaning.','#workspace/Curation','Curation')}${card('Service team','Operators manage jobs without approving source meaning.','#workspace/Administration','Administration')}</div></section><div class="notice">This is a fictional demonstration. Its requirements and cross-framework relationship are invented examples, not official PCI DSS or DORA obligations.</div>`}
function engine(){return `<div class="intro"><span class="eyebrow">The product's core</span><h1>One objective, two distinct obligations</h1><p class="lead">A shared requirement helps the company prepare once. Links back to each source preserve the part that cannot be treated as equivalent.</p></div>${matchDiagram()}<section class="section"><h2>How the system turns this into a reliable catalogue</h2><div class="pipeline">${[['1','Admit sources','Check exact versions, provenance and permitted uses.'],['2','Propose a match','Optional background AI finds a common goal and the uncovered duty.'],['3','Expert decision','A qualified person approves the exact meaning and relationships.'],['4','Guarded publication','Software rechecks rights, versions and approval, then activates the release.']].map(([n,t,c])=>`<div><span>${n}</span><b>${t}</b><p>${c}</p></div>`).join('')}</div></section><div class="grid"><div class="callout"><h3>AI is optional</h3><p>Approved content, search, evidence, permissions and publication guards work with inference switched off. Stored results are reused without a new model call on every click.</p></div><div class="callout"><h3>Change is deliberate</h3><p>A later source change enters review. Company adoption and an auditor's mission amendment remain separate decisions.</p></div></div><div class="buttons"><a class="btn" href="#tour/2">See the example match ${icon('arrow')}</a><a class="btn light" href="#tour/4">See publication safeguards</a></div>`}
function scenario(){return `<div class="intro"><span class="eyebrow">The fictional business case</span><h1>Northstar Pay, in plain language</h1><p class="lead">A French payment company prepares an access review for payment processing and merchant services. Two invented source views overlap but one needs an additional reason for retaining access.</p></div><div class="callout"><h3>The question</h3><p>Can Clara prepare the same access-review record once while Alex evaluates it separately for each audit and the extra resilience duty stays visible?</p></div>${matchDiagram()}<section class="section"><h2>Meet the people</h2><div class="grid">${card('Maya · company compliance','Defines scope and decides when the company adopts a new catalogue baseline.','#tour/0','Company')}${card('Clara · control owner','Supplies the versioned record and identifies missing population.','#tour/6','Company')}${card('Catalogue expert','Reviews source relationships and decides the exact wording.','#tour/3','Curation')}${card('Alex · lead auditor','Determines mission relevance and authorises an exact report.','#tour/7','Auditor')}</div></section><p>Start the <a href="#tour/0">guided story</a>, explore the <a href="#directory">complete module map</a>, or read the <a href="Prototype_Guide.html">standalone case guide</a>.</p><div class="notice">All obligations, mapping results, names and findings are fictional. This is not an authoritative PCI DSS–DORA mapping.</div>`}
function exampleTable(s){return `<div class="tablewrap"><table><caption>${esc(s.title)} · illustrative records</caption><thead><tr>${s.columns.map(c=>`<th scope="col">${esc(c)}</th>`).join('')}</tr></thead><tbody>${s.rows.map(r=>`<tr>${r.map((v,i)=>i?`<td>${esc(v)}</td>`:`<th scope="row">${esc(v)}</th>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function highlights(s){const views={
 SCR07:[['Proposed requirement','Exact source links and extra duty are ready for review','neutral'],['Expert decision','A qualified person must authorise the exact meaning','warn'],['Existing catalogue','Earlier approved content stays active until publication','good']],
 SCR08:[['Expert approval','Recorded for this exact proposal','good'],['Source display permission','Expired: new publication is blocked','warn'],['Automatic publication','Starts only when all current checks pass','neutral']],
 SCR12:[['Versioned file','Quarterly access review · version 1','good'],['Payment platform','April–June review supplied','good'],['Merchant services','One service still needs coverage clarification','warn']],
 SCR19:[['Card security audit','Evidence relevance considered for this mission','good'],['Resilience audit','Requires its own relevance decision','neutral'],['Uncovered duty','Reviewer justification still needed','warn']],
 SCR24:[['Company preparation','Maya reviews before adopting a new baseline','neutral'],['Active audit','Alex considers a separate mission amendment','warn'],['Issued report','Original version and recipients stay fixed','good']],
 SCR21:[['Exact report','Lead assessor reviews wording and audience','neutral'],['Client copy','Shared facts and authorised deliverables only','good'],['Private notes','Remain in the auditor workspace','warn']]
 }[s.id];return views?`<div class="highlights">${views.map(([title,copy,tone])=>`<div class="highlight ${tone}"><span>${esc(title)}</span><strong>${esc(copy)}</strong></div>`).join('')}</div>`:''}
function screen(s,index){let guided=Number.isInteger(index);return `<div class="screen-heading"><div><span class="eyebrow">${esc(roles[s.workspace])}${guided?' · Story step '+(index+1)+' of '+tour.length:''}</span><h1>${esc(guided?stages[index]:s.title)}</h1><p class="lead">${esc(s.story)}</p></div><span class="screen-icon">${icon(s.workspace)}</span></div>${guided?`<div class="progress" role="meter" aria-label="Story progress" aria-valuenow="${index+1}" aria-valuemin="0" aria-valuemax="${tour.length}"><span style="width:${Math.round((index+1)/tour.length*100)}%"></span></div>`:''}<div class="context"><span>Northstar Pay · fictional</span><span>${esc(roles[s.workspace])} view</span><span>April–June 2026 example</span></div>${s.id==='SCR05'?matchDiagram():''}${highlights(s)}<div class="workspace"><section class="panel"><div class="panel-title"><span class="eyebrow">What a user would see</span><h2>${esc(s.title)}</h2></div>${exampleTable(s)}</section><aside class="insight"><span class="eyebrow">Why this matters</span><h2>${esc(guided?takeaways[index]:s.lead)}</h2><p>${esc(s.story)}</p><button type="button" data-explain="${s.id}">What would happen? →</button></aside></div><details class="detail"><summary>See example record details</summary><dl>${s.fields.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl></details>${guided?`<nav class="story-nav" aria-label="Guided story"><a href="${index?'#tour/'+(index-1):'#scenario'}">← ${index?'Previous':'Meet the case'}</a><span>${index+1} / ${tour.length}</span><a class="btn" href="${index+1<tour.length?'#tour/'+(index+1):'#home'}">${index+1<tour.length?'Continue: '+esc(stages[index+1]):'Return to overview'} ${icon('arrow')}</a></nav>`:''}<section class="section"><h2>Related work</h2><div class="related">${s.links.map(id=>{let t=CONTENT.screens.find(x=>x.id===id);return t?`<a href="#${id}">${esc(t.title)} →</a>`:''}).join('')}</div></section>`}
function workspace(name){return `<div class="intro"><span class="eyebrow">Explore by role</span><h1>${esc(roles[name])}</h1><p class="lead">Each screen shows a concrete example, a short explanation and related work.</p></div><div class="grid">${CONTENT.screens.filter(s=>s.workspace===name).map(s=>card(s.title,s.story,'#'+s.id,name)).join('')}</div>`}
function directory(){return `<div class="intro"><span class="eyebrow">Complete target</span><h1>All product modules</h1><p class="lead">The guided case is the easiest first visit. This directory opens every illustrated product area.</p></div><div class="grid">${CONTENT.modules.map((m,i)=>card(moduleLabels[i],'Explore this part of the product through an illustrated screen.','#'+m.screens[0])).join('')}</div>`}
function render(){let route=(location.hash||'#home').slice(1),[kind,arg]=route.split('/'),body,title;if(route==='main'){$('#main').focus();return;}
 if(kind==='home'){body=home();title='Overview'}else if(kind==='engine'){body=engine();title='Matching engine'}else if(kind==='scenario'||kind==='guide'){body=scenario();title='Business case'}else if(kind==='directory'){body=directory();title='All modules'}else if(kind==='workspace'&&roles[arg]){body=workspace(arg);title=roles[arg]}
 else if(kind==='tour'&&/^\d+$/.test(arg)&&Number(arg)<tour.length){let s=CONTENT.screens.find(x=>x.id===tour[Number(arg)]);body=screen(s,Number(arg));title=stages[Number(arg)]}
 else {let s=CONTENT.screens.find(x=>x.id===kind);body=s?screen(s):'<div class="intro"><h1>View unavailable</h1><a href="#home">Back to overview</a></div>';title=s?s.title:'View unavailable'}
 $('#main').innerHTML=body;document.title=title+' · The Audit Spine';$('#main').querySelectorAll('[data-explain]').forEach(b=>b.addEventListener('click',()=>{let s=CONTENT.screens.find(x=>x.id===b.dataset.explain);$('#dialog-title').textContent='What happens at '+s.title.toLowerCase()+'?';$('#dialog-copy').textContent=s.story+' This demonstration explains the intended action; it does not create, approve or send a real record.';$('#explanation').showModal()}));window.scrollTo(0,0);$('#main').focus({preventScroll:true});}
$('#navigation').innerHTML=Object.entries(roles).map(([key,name])=>`<details><summary>${esc(name)}</summary>${CONTENT.screens.filter(s=>s.workspace===key).map(s=>`<a href="#${s.id}">${esc(s.title)}</a>`).join('')}</details>`).join('');
window.addEventListener('hashchange',render);render();
